# Change these first
owner: michalpulpan # Your GitHub organization or username, where this repository lives
repo: upptime-ecobamboo  # The name of this repository

sites:
  - name: CZ Homepage
    url: https://ecobamboo.cz
  - name: SK Homepage
    url: https://ecobamboo.sk
  - name: CZ Product page
    url: https://ecobamboo.cz/produkt/07014P-W/ecobamboo-podprsenka-s-vycpavkami-damske
  - name: CZ Category
    url: https://ecobamboo.cz/kategorie/4/zeny/kalhotky

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime-ecobamboo
  theme: dark,
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: EcoBamboo status
  introTitle: "**EcoBamboo** status monitoring page"
  introMessage: This is a status page which uses **real-time** data from EcoBamboo
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
